### ISSUE TITLE
add recipe maintainers

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/pytmatrix-feedstock#1]
Recipe maintainer volunteers somewhere :question:

@jleinonen 
@jjhelmus
@pelson
@ocefpaf

As @jleinonen is the package author, it would be good to have his experience here. We had some email conversation some time ago, regarding `pytmatrix` installation.  @pelson can be a bit more specific about conda-forge (if there are any questions etc).

Currently `pytmatrix` can be installed both in `linux` and `osx` for the python and numpy matrix. This should get most users in. As a follow up, I'll try to get some windows builds also.

**Comment by kmuehlbauer** [comment]
Thanks @ocefpaf for contributing the windows builds here (#2) and also for being maintainer.

**Comment by pelson** [comment]
I'm going to step out of this one - afraid I don't have the knowledge to be helpful beyond generic conda-forge questions. Thanks for pinging me though.

**Comment by ocefpaf** [comment]
I guess we can close this one, right @kmuehlbauer :wink:
